general {
    after_sleep_cmd = hyprctl dispatch dpms on
}

listener {
    timeout = 300                # 5 Menit otomatis ngunci
    on-timeout = QUICKSHELL_PRIVILEGED=1 QML_XHR_ALLOW_FILE_READ=1 quickshell --path ~/.config/Sreetx-Neo/component/LockScreen.qml
}

listener {
    timeout = 360                               # 6 Menit layar mati
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

listener {
    timeout = 600                               # 600 detik = 10 Menit nganggur
    on-timeout = systemctl suspend              # Paksa laptop masuk mode sleep
}
