$hypr = ~/.config/hypr
$hl = $hypr/hyprland

# Components 
source = $hl/general.conf
source = $hl/rules.conf
source = $hl/execs.conf
source = $hl/env.conf
source = $hl/keybinds.conf

# Default monitor config path
source = $hypr/monitors.conf
