-- Generated by nwg-displays on 2026-06-02 at 19:31:04. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "1920x1080@60.05",
    position = "982x0",
    scale = 1.0
})
hl.monitor({
    output = "HDMI-A-2",
    mode = "1366x768@59.96",
    position = "0x0",
    scale = 1.0,
    transform = 1
})
