# CORE
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = hypridle

exec-once = QUICKSHELL_PRIVILEGED=1 QML_XHR_ALLOW_FILE_READ=1 quickshell --path ~/.config/Sreetx-Neo/sreetx.qml

# Another
exec-once = easyeffects --gapplication-service
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = hyprctl setcursor Skirk Cursors 32
