monitor=,preferred,auto,1

# --- INPUT & TOUCHPAD ---
input {
    kb_layout = us
    follow_mouse = 1
    touchpad {
        natural_scroll = true # Scroll kebalik ala macOS/Windows
        tap-to-click = true
        disable_while_typing = true
    }
    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
}

# --- DEKORASI ---
general {
    gaps_in = 5
    gaps_out = 8
    border_size = 2
    col.active_border = rgba(00E5FFaa) rgba(00E5FFff) 45deg # Cyan Sreetx-Neo
    col.inactive_border = rgba(595959aa)
    layout = dwindle
}

dwindle {
    preserve_split = true
    smart_resizing = true
    force_split = 2 
}

decoration {
    dim_special = 0.2
    rounding = 12 # Bikin sudut jendela lebih membulat manis
    
    # Efek Blur (Ini yang bikin jadi "keren")
    blur {
        enabled = true
        size = 8        # Semakin gede, blur semakin "tebel"
        passes = 3      # Semakin banyak, blur semakin halus & jernih (rekomendasi 3 buat performa)
        new_optimizations = true # Wajib ON biar gak nge-lag
        ignore_opacity = true    # Biar blur tembus ke jendela yang transparan
        special = true
    }
}

animations {
    enabled = true
    
    # Kurva gerakan (Bezier) - Angka ini "magic number" buat animasi smooth
    bezier = overshot, 0.05, 0.9, 0.1, 1.1 
    bezier = smoothOut, 0.36, 0, 0.66, -0.56
    bezier = jembod_elegant, 0.22, 1, 0.36, 1
    bezier = runCurve, 0.1, 1, 0.1, 1
    
    # Animasi Jendela
    animation = windows, 1, 5, overshot, slidevert, popin 90%    # Jendela masuk: muncul dengan efek "membal"
    animation = windowsOut, 1, 5, overshot, popin 80% # Jendela keluar
    animation = border, 1, 10, default                 # Animasi border aktif
    animation = fade, 1, 5, default                    # Efek fade in/out
    animation = workspaces, 1, 5, overshot, slidevert  # Animasi ganti workspace (slide vertikal)
    animation = specialWorkspace, 1, 5, overshot, slidevert
}
