$S = SUPER

# Apps & Features
bind = $S, Return, exec, kitty
bind = $S, T, exec, kitty
bind = $S, Q, killactive, 
bind = $S, E, exec, nautilus
bind = $S, W, exec, google-chrome-stable
bind = $S, ALT + Space, togglefloating
bind = $S, SUPER_L, exec, rofi -show drun -theme ~/.config/rofi/sreetx-neo.rasi 
bind = SUPER, L, exec, QUICKSHELL_PRIVILEGED=1 QML_XHR_ALLOW_FILE_READ=1 quickshell --path ~/.config/Sreetx-Neo/component/LockScreen.qml

#hyprctl dispatch global quickshell:openSuper

bind = $S, P, pseudo, # dwindle
bind = $S, period, exec, rofimoji --selector-args "-theme ~/.config/rofi/sreetx-neo.rasi" --action copy --clipboarder wl-copy
bind = $S SHIFT, S, exec, grimblast copy area
bind = $S, V, exec, cliphist list | wofi --dmenu --style ~/.config/rofi/sreetx-neo.css | cliphist decode | wl-copy
bindr = $S, R, exec, QUICKSHELL_PRIVILEGED=1 quickshell --path ~/.config/Sreetx-Neo/component/Apps/Run.qml

# --- MEDIA & VOLUME CONTROL (TERINTEGRASI QUICKSHELL) ---
# Volume (F1 - F3)
bindl = , XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle && notify-send -a "Volume" "0"
bindel = , XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%- && notify-send -a "Volume" "$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | awk '{print int($2*100)}')"
bindel = , XF86AudioRaiseVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+ -l 1.0 && notify-send -a "Volume" "$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | awk '{print int($2*100)}')"

# Mic
bind = , XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle && \
  bash -c 'status=$(wpctl get-volume @DEFAULT_AUDIO_SOURCE@ | grep -o "MUTED"); \
  if [ -z "$status" ]; then notify-send -a "Mic" "unmuted"; else notify-send -a "Mic" "muted"; fi'

# Brightness (F5 - F6)
bind = , XF86MonBrightnessUp, exec, brightnessctl set +5% && notify-send -a "Brightness" "$(brightnessctl -m | cut -d, -f4 | tr -d '%')"
bind = , XF86MonBrightnessDown, exec, brightnessctl set 5%- && notify-send -a "Brightness" "$(brightnessctl -m | cut -d, -f4 | tr -d '%')"

# --- WINDOW MANAGEMENT ---
bind = $S, left, movefocus, l
bind = $S, right, movefocus, r
bind = $S, up, movefocus, u
bind = $S, down, movefocus, d
bind = $S, F, fullscreen, 0
bind = $S, D, fullscreen, 1

# Workspace Switching (1-10)
bind = $S, 1, workspace, 1
bind = $S, 2, workspace, 2
bind = $S, 3, workspace, 3
bind = $S, 4, workspace, 4
bind = $S, 5, workspace, 5
bind = $S, 6, workspace, 6
bind = $S, 7, workspace, 7
bind = $S, 8, workspace, 8
bind = $S, 9, workspace, 9
bind = $S, 0, workspace, 10

# Move windows to another workspace
bind = $S SHIFT, 1, movetoworkspace, 1
bind = $S SHIFT, 2, movetoworkspace, 2
bind = $S SHIFT, 3, movetoworkspace, 3
bind = $S SHIFT, 4, movetoworkspace, 4 
bind = $S SHIFT, 5, movetoworkspace, 5 
bind = $S SHIFT, 6, movetoworkspace, 6 
bind = $S SHIFT, 7, movetoworkspace, 7 
bind = $S SHIFT, 8, movetoworkspace, 8 
bind = $S SHIFT, 9, movetoworkspace, 9
bind = $S SHIFT, 0, movetoworkspace, 10 
bind = $S SHIFT, mouse_up, movetoworkspace, +1
bind = $S SHIFT, mouse_down, movetoworkspace, -1

# Window Groups
bind = $S, G, togglegroup 
bind = $S, S, togglespecialworkspace, Special1 
bind = $S, M, togglespecialworkspace, Music
bind = $S, Z, togglespecialworkspace, RecordArea

# Workspace Move with Mouse scroll
bind = $S, mouse_up, workspace, +1
bind = $S, mouse_down, workspace, -1

# Window Layout edit
bindm = $S, mouse:272, movewindow
bindm = $S, mouse:273, resizewindow
bind = $S SHIFT, left, movewindow, l
bind = $S SHIFT, right, movewindow, r
bind = $S SHIFT, down, movewindow, d
bind = $S SHIFT, up, movewindow, u
bind = $S ALT, SPACE, togglefloating

# Logout-Menu
bind = $S SHIFT ALT, P, exec, systemctl poweroff
bind = $S SHIFT ALT, R, exec, systemctl reboot
bind = $S SHIFT ALT, L, exit,

