windowrule = opaque true, match:class foot|equibop|org\.quickshell|imv|swappy  # They use native transparency or we want them opaque
windowrule = center true, match:float true, match:xwayland false  # Center all floating windows (not xwayland cause popups) 

# Floatin apps
windowrule = match:class ^(pavucontrol)$, float on, center on, size {900 500}
windowrule = float on, center on, match:class ^(blueman-manager)$, size {900 600} 
windowrule = match:class ^(quickshell)$, float on, center on, size {1100 650}
windowrule = match:class ^(Mission Center)$, float on, center on, size {1100 650}

# Quickshell Layer
layerrule = blur 1, match:class ^(quickshell.*)$
layerrule = ignore_alpha 0.3, match:class ^(quickshell.*)$
layerrule = animation 4 overshot slidevert, match:class ^(quickshell.*)$
